[build]
  publish = "."

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

[context.production.environment]
  NODE_VERSION = "18"

# Headers to prevent caching of script.js
[[headers]]
  for = "/script.js*"
  [headers.values]
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" 