[build]
  publish = "."

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"

# Form handling - emails will be sent to the configured email
# You'll need to configure this in Netlify admin panel:
# Site Settings > Forms > Form notifications
# Add espana.dsr@gmail.com as the notification email 